Repository eclipse-ee4j/jersey, pull requests merged in 2019-04, with the labels that each got.

#3983 Upgrade Netty and expose Netty Context
  containers/netty-http/src/main/java/org/glassfish/jersey/netty/httpserver/HttpVersionChooser.java
  containers/netty-http/src/main/java/org/glassfish/jersey/netty/httpserver/JerseyServerHandler.java
  containers/netty-http/src/main/java/org/glassfish/jersey/netty/httpserver/JerseyServerInitializer.java
  containers/netty-http/src/main/java/org/glassfish/jersey/netty/httpserver/NettySecurityContext.java
  pom.xml
Labels: 2.29, netty

#4079 Update hk2 osgi-resource-locator to latest 1.0.3 version
  pom.xml
  tests/osgi/functional/src/test/java/org/glassfish/jersey/osgi/test/basic/JsonJettisonTest.java
  tests/osgi/functional/src/test/java/org/glassfish/jersey/osgi/test/basic/WebResourceFactoryTest.java
Labels: 2.29

#3839 Support for JAX-RS 2.2 Java SE Bootstrapping API
  containers/grizzly2-http/pom.xml
  containers/grizzly2-http/src/main/java/org/glassfish/jersey/grizzly2/httpserver/GrizzlyHttpServer.java
  containers/grizzly2-http/src/main/java/org/glassfish/jersey/grizzly2/httpserver/GrizzlyHttpServerProvider.java
  containers/grizzly2-http/src/main/resources/META-INF/services/org.glassfish.jersey.server.spi.ServerProvider
  containers/grizzly2-http/src/test/java/org/glassfish/jersey/grizzly2/httpserver/GrizzlyHttpServerProviderTest.java
  containers/jdk-http/pom.xml
  containers/jdk-http/src/main/java/org/glassfish/jersey/jdkhttp/JdkHttpServer.java
  containers/jdk-http/src/main/java/org/glassfish/jersey/jdkhttp/JdkHttpServerFactory.java
  containers/jdk-http/src/main/java/org/glassfish/jersey/jdkhttp/JdkHttpServerProvider.java
  containers/jdk-http/src/main/resources/META-INF/services/org.glassfish.jersey.server.spi.ServerProvider
  containers/jdk-http/src/test/java/org/glassfish/jersey/jdkhttp/AbstractJdkHttpServerTester.java
  containers/jdk-http/src/test/java/org/glassfish/jersey/jdkhttp/JdkHttpServerProviderTest.java
  containers/jdk-http/src/test/java/org/glassfish/jersey/jdkhttp/JdkHttpsServerTest.java
  containers/jetty-http/pom.xml
  containers/jetty-http/src/main/java/org/glassfish/jersey/jetty/JettyHttpServer.java
  containers/jetty-http/src/main/java/org/glassfish/jersey/jetty/JettyHttpServerProvider.java
  containers/jetty-http/src/main/resources/META-INF/services/org.glassfish.jersey.server.spi.ServerProvider
  containers/jetty-http/src/test/java/org/glassfish/jersey/jetty/AbstractJettyServerTester.java
  containers/jetty-http/src/test/java/org/glassfish/jersey/jetty/JettyHttpServerProviderTest.java
  containers/netty-http/pom.xml
  containers/netty-http/src/main/java/org/glassfish/jersey/netty/httpserver/NettyHttpContainerProvider.java
  containers/netty-http/src/main/java/org/glassfish/jersey/netty/httpserver/NettyHttpServer.java
  containers/netty-http/src/main/java/org/glassfish/jersey/netty/httpserver/NettyHttpServerProvider.java
  containers/netty-http/src/main/resources/META-INF/services/org.glassfish.jersey.server.spi.ServerProvider
  containers/netty-http/src/test/java/org/glassfish/jersey/netty/httpserver/NettyHttpServerProviderTest.java
  containers/simple-http/pom.xml
  containers/simple-http/src/main/java/org/glassfish/jersey/simple/SimpleContainerFactory.java
  containers/simple-http/src/main/java/org/glassfish/jersey/simple/SimpleHttpServer.java
  containers/simple-http/src/main/java/org/glassfish/jersey/simple/SimpleHttpServerProvider.java
  containers/simple-http/src/main/java/org/glassfish/jersey/simple/SimpleServer.java
  containers/simple-http/src/main/resources/META-INF/services/org.glassfish.jersey.server.spi.ServerProvider
  containers/simple-http/src/test/java/org/glassfish/jersey/simple/AbstractSimpleServerTester.java
  containers/simple-http/src/test/java/org/glassfish/jersey/simple/SimpleHttpServerProviderTest.java
  core-server/src/main/java/org/glassfish/jersey/server/ServerFactory.java
  core-server/src/main/java/org/glassfish/jersey/server/ServerProperties.java
  core-server/src/main/java/org/glassfish/jersey/server/internal/RuntimeDelegateImpl.java
  core-server/src/main/java/org/glassfish/jersey/server/spi/Server.java
  core-server/src/main/java/org/glassfish/jersey/server/spi/ServerProvider.java
  core-server/src/test/java/org/glassfish/jersey/server/ServerFactoryTest.java
  core-server/src/test/java/org/glassfish/jersey/server/internal/RuntimeDelegateImplTest.java
Labels: 2.30
