Repository eclipse-ee4j/jersey, pull requests merged in 2021-12, with the labels that each got.

#4924 Refactor processResponseError in ServerRuntime
  core-server/src/main/java/org/glassfish/jersey/server/ServerRuntime.java
Labels: refactoring

#4923 Documentation for the default Exception mapper
  docs/src/main/docbook/jersey.ent
  docs/src/main/docbook/representations.xml
Labels: documentation

#4940 Issue #4881 - Java client connector
  bom/pom.xml
  connectors/java-connector/pom.xml
  connectors/java-connector/src/main/java/org/glassfish/jersey/java/connector/JavaClientProperties.java
  connectors/java-connector/src/main/java/org/glassfish/jersey/java/connector/JavaConnector.java
  connectors/java-connector/src/main/java/org/glassfish/jersey/java/connector/JavaConnectorProvider.java
  connectors/java-connector/src/main/java/org/glassfish/jersey/java/connector/package-info.java
  connectors/java-connector/src/main/resources/org/glassfish/jersey/java/connector/localization.properties
  connectors/java-connector/src/test/java/org/glassfish/jersey/java/connector/AbstractJavaConnectorTest.java
  connectors/java-connector/src/test/java/org/glassfish/jersey/java/connector/AsyncTest.java
  connectors/java-connector/src/test/java/org/glassfish/jersey/java/connector/BodyPublisherTest.java
  connectors/java-connector/src/test/java/org/glassfish/jersey/java/connector/OptionsMethodTest.java
  connectors/java-connector/src/test/java/org/glassfish/jersey/java/connector/RedirectTest.java
  connectors/java-connector/src/test/java/org/glassfish/jersey/java/connector/RetrieveHttpClientFromConnectorProviderTest.java
  connectors/pom.xml
  pom.xml
Labels: CQ required
