Repository eclipse-ee4j/jersey, pull requests merged in 2021-01, with the labels that each got.

#4653 Jakartified User Guide - first 10 chapters
  docs/pom.xml
  docs/src/main/docbook/client.xml
  docs/src/main/docbook/dependencies.xml
  docs/src/main/docbook/deployment.xml
  docs/src/main/docbook/getting-started.xml
  docs/src/main/docbook/jaxrs-resources.xml
  docs/src/main/docbook/jersey.ent
  docs/src/main/docbook/mbw.xml
  docs/src/main/docbook/representations.xml
  docs/src/main/docbook/rx-client.xml
  docs/src/main/docbook/user-guide.xml
Labels: documentation

#4656 Jakartified User Guide - second 10 chapters
  docs/src/main/docbook/async.xml
  docs/src/main/docbook/bean-validation.xml
  docs/src/main/docbook/client.xml
  docs/src/main/docbook/deployment.xml
  docs/src/main/docbook/entity-filtering.xml
  docs/src/main/docbook/filters.xml
  docs/src/main/docbook/getting-started.xml
  docs/src/main/docbook/jersey.ent
  docs/src/main/docbook/media.xml
  docs/src/main/docbook/mp-config.xml
  docs/src/main/docbook/resource-builder.xml
  docs/src/main/docbook/sse.xml
  docs/src/main/docbook/uris-and-links.xml
Labels: documentation

#4657 Jakartified User Guide - final 10 chapters with appendix-properties adjusted
  docs/src/main/docbook/appendix-properties.xml
  docs/src/main/docbook/cdi.xml
  docs/src/main/docbook/custom-di.xml
  docs/src/main/docbook/how-to-build.xml
  docs/src/main/docbook/jersey.ent
  docs/src/main/docbook/logging.xml
  docs/src/main/docbook/mbw.xml
  docs/src/main/docbook/migration.xml
  docs/src/main/docbook/monitoring.xml
  docs/src/main/docbook/mvc.xml
  docs/src/main/docbook/security.xml
  docs/src/main/docbook/test-framework.xml
  docs/src/main/docbook/user-guide.xml
  docs/src/main/docbook/wadl.xml
Labels: documentation

#4662 #4658 Apache HttpComponents upgrade
  pom.xml
Labels: CQ required

#4680 2.x apidocs bundle generation fixes
  bundles/apidocs/pom.xml
  pom.xml
Labels: documentation

#4676 jakartified modules.xml from User Guide
  docs/src/main/docbook/modules.xml
Labels: documentation

#4647 Add support RFC 5987 for attribute filename* in HTTP header Content-Disposition
  media/multipart/src/main/java/org/glassfish/jersey/media/multipart/ContentDisposition.java
  tests/e2e/src/test/java/org/glassfish/jersey/tests/api/ContentDispositionTest.java
Labels: Type: Improvement

#4639 Chapter for Expect:100-continue header (client)
  docs/src/main/docbook/client.xml
Labels: documentation
