Repository eclipse-ee4j/jersey, pull requests merged in 2024-04, with the labels that each got.

#5596 initial 4.x documentation changes
  docs/src/main/docbook/appendix-properties.xml
  docs/src/main/docbook/client.xml
  docs/src/main/docbook/dependencies.xml
  docs/src/main/docbook/migration.xml
  docs/src/main/docbook/modules.xml
Labels: documentation

#5592 Micrometer - Add missing metrics for cases of client errors
  ext/micrometer/src/main/java/org/glassfish/jersey/micrometer/server/JerseyTags.java
  ext/micrometer/src/main/java/org/glassfish/jersey/micrometer/server/MetricsRequestEventListener.java
  ext/micrometer/src/test/java/org/glassfish/jersey/micrometer/server/DefaultJerseyTagsProviderTest.java
  ext/micrometer/src/test/java/org/glassfish/jersey/micrometer/server/MetricsRequestEventListenerTest.java
  ext/micrometer/src/test/java/org/glassfish/jersey/micrometer/server/resources/TestResource.java
Labels: micrometer

#5625 align CONTRIBUTING.md with Eclipse actual requirements
  CONTRIBUTING.md
Labels: documentation, LEGAL
