Repository eclipse-ee4j/jersey, pull requests merged in 2025-07, with the labels that each got.

#5945 Jackson update to 2.19.1
  NOTICE.md
  examples/NOTICE.md
  media/json-jackson/src/main/java/org/glassfish/jersey/jackson/internal/jackson/jaxrs/base/ProviderBase.java
  media/json-jackson/src/main/java/org/glassfish/jersey/jackson/internal/jackson/jaxrs/json/JacksonJsonProvider.java
  media/json-jackson/src/main/java/org/glassfish/jersey/jackson/internal/jackson/jaxrs/json/JsonMapperConfigurator.java
  media/json-jackson/src/main/java/org/glassfish/jersey/jackson/internal/jackson/jaxrs/json/PackageVersion.java
  media/json-jackson/src/main/resources/META-INF/NOTICE.markdown
  pom.xml
Labels: json-jackson, 2.x

#5955 Updated release process [ossrh]
  examples/oauth-client-twitter/pom.xml
  ext/micrometer/pom.xml
  ext/microprofile/mp-config/pom.xml
  ext/microprofile/mp-rest-client/pom.xml
  ext/microprofile/pom.xml
  pom.xml
  security/oauth1-server/pom.xml
  security/oauth1-signature/pom.xml
  security/oauth2-client/pom.xml
Labels: 3.1

#5952 Useless exception when client closes stream whilst response transfer …
  core-server/src/main/java/org/glassfish/jersey/server/ServerRuntime.java
Labels: 2.x
